Add PHPDoc and reformat
conekta/conekta-php pull request #205
Opened 2022-06-21 01:23 UTC by Perafan18

Add PHPDoc, this helps code editors and helps to have code that is better understood

2022-09-13 20:34 UTC, afalla-conekta approved these changes

2022-09-13 20:44 UTC, ElvisHeredia approved these changes

2022-09-21 21:08 UTC, ElvisHeredia requested changes

2022-09-21 21:08 UTC, ElvisHeredia commented on lib/Conekta/Address.php
> +     * @var string
Para ahorrarte los comentarios de este tipo puedes definir el tipo al declara la variable así:
``pubic string $street1 = '';``
No estoy seguro pero podrias omitir el ``=''`` al definir la variable así :
``pubic ?string $street1;`` 
pero esto último habría que probarlo

2022-09-30 06:59 UTC, Perafan18 commented on lib/Conekta/Address.php
> +     * @var string
Decidí omitir el explicit type en las variables, creo que necesitaríamos hacer una análisis más detallado ya que hay variables que pueden ser string y null, string y object o string e int y al asignarle un type las pruebas fallas. 

Aunque les asigne el type "correcto" y las pruebas funcionen no estoy seguro de hacer ese cambio ahorita, necesitaríamos hacer más pruebas.

2023-07-19 20:43 UTC, closed without merging